name: dashboard
region: nyc
domains:
- domain: my.datacue.co
  type: PRIMARY
static_sites:
- environment_slug: html
  github:
    branch: dist
    deploy_on_push: true
    repo: DataCueCo/dashboard
  name: dashboard
  routes:
  - path: /
  index_document: index.html
  error_document: index.html
