name: dashboard-staging
region: nyc
domains:
- domain: my-staging.datacue.co
  type: PRIMARY
static_sites:
- environment_slug: html
  github:
    branch: dist-staging
    deploy_on_push: true
    repo: DataCueCo/dashboard
  name: dashboard-staging
  routes:
  - path: /
  index_document: index.html
  error_document: index.html
